#!/bin/bash
#
# sudo npm install uglify-js -g
#

rm -rf dist
rm -rf images
rm -rf img
mkdir dist
mkdir images
mkdir img

#ckeditor/ckeditor.js \
# Javascripts
uglifyjs --lint\
  \
  assets/plugins/jquery-migrate-1.2.1.min.js \
  assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js \
  assets/plugins/bootstrap/js/bootstrap.min.js \
  assets/plugins/bootstrap/js/bootstrap2-typeahead.min.js \
  assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js \
  assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js \
  assets/plugins/jquery.blockui.min.js \
  assets/plugins/jquery.cookie.min.js \
  assets/plugins/uniform/jquery.uniform.min.js \
  \
  assets/plugins/fuelux/js/spinner.min.js \
  assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js \
  assets/plugins/select2/select2.js \
  assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js \
  assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js \
  assets/plugins/clockface/js/clockface.js \
  assets/plugins/bootstrap-daterangepicker/moment.min.js \
  assets/plugins/bootstrap-daterangepicker/daterangepicker.js \
  assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js \
  assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js \
  assets/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js \
  assets/plugins/jquery.input-ip-address-control-1.0.min.js \
  assets/plugins/jquery-multi-select/js/jquery.multi-select.js \
  assets/plugins/jquery-multi-select/js/jquery.quicksearch.js \
  assets/plugins/jquery.pwstrength.bootstrap/src/pwstrength.js \
  assets/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js \
  assets/plugins/bootstrap-markdown/js/bootstrap-markdown.js \
  assets/plugins/bootstrap-markdown/lib/markdown.js \
  assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js \
  assets/plugins/jquery-validation/dist/jquery.validate.min.js \
  assets/plugins/jquery-validation/dist/additional-methods.min.js \
  \
  assets/plugins/data-tables/jquery.dataTables.js \
  assets-misc/jquery.dataTables.rowReordering.js \
  assets-misc/bootbox.min.js \
  assets/plugins/data-tables/DT_bootstrap.js \
  assets/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.js \
  \
  assets/scripts/app.js \
  \
  -o dist/admin.min.js
cat dist/admin.min.js | gzip -9 > dist/admin.min.js.gz

# Stylesheets
cat \
  assets/plugins/bootstrap/css/bootstrap.min.css \
  assets/plugins/uniform/css/uniform.default.css \
  \
  assets/plugins/select2/select2_conquer.css \
  assets/plugins/data-tables/DT_bootstrap.css \
  assets/plugins/bootstrap-fileupload/bootstrap-fileupload.css \
  assets/plugins/gritter/css/jquery.gritter.css \
  assets/plugins/select2/select2_conquer.css \
  assets/plugins/clockface/css/clockface.css \
  assets/plugins/bootstrap-datepicker/css/datepicker.css \
  assets/plugins/bootstrap-timepicker/compiled/timepicker.css \
  assets/plugins/bootstrap-colorpicker/css/colorpicker.css \
  assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css \
  assets/plugins/bootstrap-datetimepicker/css/datetimepicker.css \
  assets/plugins/jquery-multi-select/css/multi-select.css \
  assets/plugins/bootstrap-switch/static/stylesheets/bootstrap-switch-conquer.css \
  assets/plugins/bootstrap-markdown/css/bootstrap-markdown.min.css \
  assets/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css \
  \
  assets/css/style-conquer.css \
  assets/css/style.css \
  assets/css/style-responsive.css \
  assets/css/plugins.css \
  assets/css/themes/default.css \
  assets/css/pages/error.css \
  assets/css/custom.css \
  > dist/admin.css

sass -t compressed --scss dist/admin.css dist/admin.min.css
rm dist/admin.css
cat dist/admin.min.css | gzip -9 > dist/admin.min.css.gz

mkdir dist/images
cp assets/plugins/data-tables/images/* dist/images/
cp assets/plugins/select2/*.png dist/
cp assets/plugins/select2/*.gif dist/
cp assets/plugins/uniform/images/*.png images/
cp assets/plugins/bootstrap-editable/bootstrap-editable/img/* img/
cp assets/img/remove-icon-small.png img/
